#pragma once

void InitItem();
void InitJewel();
void InitWing();
void ItemModelLoad();
void ItemTextureLoad();
void LoadItemModel(int index,char* folder,char* name);
void LoadItemTexture(int index,char* folder);
void GetItemColor(DWORD a,DWORD b,DWORD c,DWORD d,DWORD e);
void GetItemEffect(DWORD a,int b,float* c,float d,int e,int f,int g,int h,int i);
void DrawItemToolTip(DWORD address);
bool MoveItem(DWORD a,DWORD b,int c,int d,int e);
void GetItemToolTip();
void JewelCheckApplyItem1();
void JewelCheckApplyItem2();
void JewelCheckIndex1();
void JewelCheckIndex2();
void JewelCheckIndex3();
void WingMakePreviewCharSet();
void WingDisableLevelGlow();
void WingSetIncDamage();
void WingSetDecDamage();
void WingSetDefense();
void WingSetExtraDefense();
void WingSetOption();
void WingSetNewOption();
void WingSetModelType();
void WingCheckIndex1();
void WingCheckIndex2();
void WingCheckIndex3();
void WingCheckIndex4();
void WingCheckIndex5();
void WingCheckIndex6();
void WingCheckIndex7();
void WingCheckIndex8();
void WingCheckIndex9();
void WingCheckIndex10();
void WingCheckIndex11();
void WingCheckIndex12();
void WingCheckIndex13();
void WingCheckIndex14();
void WingCheckIndex15();
void WingCheckIndex16();
void WingCheckIndex17();
void WingCheckIndex18();
void WingCheckIndex19();
void WingCheckIndex20();
void WingCheckIndex21();
void WingCheckIndex22();
void WingCheckIndex23();
void WingCheckIndex24();
void WingCheckIndex25();
void WingCheckIndex26();
void WingCheckIndex27();
void WingCheckIndex28();
void WingCheckModelIndex1();
void WingCheckModelIndex2();
void WingCheckModelIndex3();